### PR TITLE
Pipeline

### PR DESCRIPTION
**Pull request by ilteoood**
Here is a PR to create a pipeline that will automatically push on Docker Hub the container related to the base dockerfile.

You should change only the image name

### CODE REVIEW

**Comment by m1k1o** [comment]
Thank you for your contribution. I might just use the same workflow from my other project, in order to have it unified, e.g:

https://github.com/m1k1o/blog/blob/dabfd027763c91a0cbd3e06cee97ba8e7d531fbb/.github/workflows/build.yml

**Comment by ilteoood** [comment]
But that doesn't create a multi-arch docker image.
For example, with that flow I can't run it on a raspberry pi

**Comment by m1k1o** [comment]
That is a fair point, I'll look into that.

**Comment by ilteoood** [comment]
Has been a while, any news about this?

**Comment by m1k1o** [comment]
Sorry for the delay, I forgot about this. Looks good.

**Comment by m1k1o** [comment]
Oh right, I forgot. I'd rather host it on github packages because dockerhub with their pricing and rate limiting is annoying.

**Comment by ilteoood** [comment]
Instead of reverting this, you could configure the  docker Server parameter

**Comment by m1k1o** [comment]
You are right.

**Comment by m1k1o** [comment]
It's working now.

**Comment by ilteoood** [comment]
Thank you so much

**Pull request merged**
